# Warcraft 3 imports file
version = 1

[[imports]]
path_type = 8
path = 'war3mapImported/questionmark_item.mdx'

[[imports]]
path_type = 13
path = 'apimports\eviljaina.mdx'

[[imports]]
path_type = 13
path = 'apimports\eviljaina_portrait.mdx'

[[imports]]
path_type = 13
path = 'apimports\eviljaina.blp'

[[imports]]
path_type = 13
path = 'apimports\evilmuradin.mdx'

[[imports]]
path_type = 13
path = 'apimports\evilmuradin_portrait.mdx'

[[imports]]
path_type = 13
path = 'apimports\evilmountainking.blp'

[[imports]]
path_type = 13
path = 'apimports\evilpaladin.mdx'

[[imports]]
path_type = 13
path = 'apimports\evilpaladin_portrait.mdx'

[[imports]]
path_type = 13
path = 'apimports\evilpaladin.blp'

[[imports]]
path_type = 13
path = 'apimports\evilkael.mdx'

[[imports]]
path_type = 13
path = 'apimports\evilkael_portrait.mdx'

[[imports]]
path_type = 13
path = 'apimports\evilkael.blp'
