# Warcraft 3 imports file
version = 1

[[imports]]
path_type = 8
path = 'war3mapImported/questionmark_item.mdx'

[[imports]]
path_type = 13
path = 'apimports\eviljaina.mdx'

[[imports]]
path_type = 13
path = 'apimports\eviljaina_portrait.mdx'

[[imports]]
path_type = 13
path = 'apimports\eviljaina.blp'
