# Warcraft 3 Sound file (.w3s)
# See w3s.py for type definitions

version = 1

[[sounds]]

name = 'gg_snd_H09Arthas02'
file = 'Sound\Dialogue\HumanCampaign\Human09\H09Arthas02.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H09Arthas05'
file = 'Sound\Dialogue\HumanCampaign\Human09\H09Arthas05.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H09Arthas07'
file = 'Sound\Dialogue\HumanCampaign\Human09\H09Arthas07.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H09Arthas09'
file = 'Sound\Dialogue\HumanCampaign\Human09\H09Arthas09.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H09Arthas12'
file = 'Sound\Dialogue\HumanCampaign\Human09\H09Arthas12.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H09Arthas14'
file = 'Sound\Dialogue\HumanCampaign\Human09\H09Arthas14.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H09Arthas16'
file = 'Sound\Dialogue\HumanCampaign\Human09\H09Arthas16.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H09Arthas18'
file = 'Sound\Dialogue\HumanCampaign\Human09\H09Arthas18.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H09Arthas19'
file = 'Sound\Dialogue\HumanCampaign\Human09\H09Arthas19.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H09Arthas21'
file = 'Sound\Dialogue\HumanCampaign\Human09\H09Arthas21.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H09Arthas24'
file = 'Sound\Dialogue\HumanCampaign\Human09\H09Arthas24.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H09Arthas26'
file = 'Sound\Dialogue\HumanCampaign\Human09\H09Arthas26.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H09Arthas28'
file = 'Sound\Dialogue\HumanCampaign\Human09\H09Arthas28.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H09Captain20'
file = 'Sound\Dialogue\HumanCampaign\Human09\H09Captain20.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H09Guardian08'
file = 'Sound\Dialogue\HumanCampaign\Human09\H09Guardian08.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H09Guardian10'
file = 'Sound\Dialogue\HumanCampaign\Human09\H09Guardian10.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H09Guardian11'
file = 'Sound\Dialogue\HumanCampaign\Human09\H09Guardian11.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H09Guardian13'
file = 'Sound\Dialogue\HumanCampaign\Human09\H09Guardian13.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H09MalGanis03'
file = 'Sound\Dialogue\HumanCampaign\Human09\H09MalGanis03.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H09MalGanis23'
file = 'Sound\Dialogue\HumanCampaign\Human09\H09MalGanis23.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H09MalGanis25'
file = 'Sound\Dialogue\HumanCampaign\Human09\H09MalGanis25.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H09MalGanis27'
file = 'Sound\Dialogue\HumanCampaign\Human09\H09MalGanis27.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H09Muradin01'
file = 'Sound\Dialogue\HumanCampaign\Human09\H09Muradin01.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H09Muradin04'
file = 'Sound\Dialogue\HumanCampaign\Human09\H09Muradin04.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H09Muradin06'
file = 'Sound\Dialogue\HumanCampaign\Human09\H09Muradin06.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H09Muradin15'
file = 'Sound\Dialogue\HumanCampaign\Human09\H09Muradin15.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H09Muradin17'
file = 'Sound\Dialogue\HumanCampaign\Human09\H09Muradin17.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_QuestNew'
file = 'Sound\Interface\QuestNew.wav'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_QuestLog'
file = 'Sound\Interface\QuestLog.wav'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_QuestFailed'
file = 'Sound\Interface\QuestFailed.wav'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_QuestCompleted'
file = 'Sound\Interface\QuestCompleted.wav'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_Hint'
file = 'Sound\Interface\Hint.wav'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_MassTeleportTarget'
file = 'Abilities\Spells\Human\MassTeleport\MassTeleportTarget.wav'
effects = 'SpellsEAX'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_HorseLoop1'
file = 'Units\Human\Knight\HorseLoop1.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_HorseLoop2'
file = 'Units\Human\Knight\HorseLoop2.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_HorseLoop3'
file = 'Units\Human\Knight\HorseLoop3.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_HeroMountainKingDeath'
file = 'Units\Human\HeroMountainKing\HeroMountainKingDeath.wav'
effects = 'HeroAcksEAX'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_ColdArrow2'
file = 'Abilities\Weapons\ColdArrow\ColdArrow2.wav'
effects = 'MissilesEAX'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_DryadMissile2'
file = 'Abilities\Weapons\Dryadmissile\DryadMissile2.wav'
effects = 'MissilesEAX'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_DivineShield'
file = 'Abilities\Spells\Human\DivineShield\DivineShield.wav'
effects = 'SpellsEAX'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_BalrogAttack1'
file = 'Units\Demon\DoomGuard\BalrogAttack1.wav'
effects = 'CombatSoundsEAX'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_FrostArmorTarget1'
file = 'Abilities\Spells\Undead\FrostArmor\FrostArmorTarget1.wav'
effects = 'SpellsEAX'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_FrostmourneLoopUndead01'
file = 'Sound\Ambient\DoodadEffects\FrostmourneLoopUndead01.wav'
effects = 'DoodadsEAX'
flags = "Looping|Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H09Arthas28a'
file = 'Sound\Dialogue\HumanCampaign\Human09\H09Arthas28a.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_GargoyleWhat1'
file = 'Units\Undead\Gargoyle\GargoyleWhat1.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_GargoyleWhat2'
file = 'Units\Undead\Gargoyle\GargoyleWhat2.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_HumanCallToArmsWhat1'
file = 'Abilities\Spells\Human\CallToArms\HumanCallToArmsWhat1.wav'
effects = 'SpellsEAX'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_AbominationYesAttack2'
file = 'Units\Undead\Abomination\AbominationYesAttack2.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_CityScapeMagicRunesLoop1'
file = 'Sound\Ambient\DoodadEffects\CityScapeMagicRunesLoop1.wav'
effects = 'DoodadsEAX'
flags = "Looping|Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_FrostmourneChant1'
file = 'Sound\Ambient\DoodadEffects\FrostmourneChant1.wav'
effects = 'DefaultEAXON'
flags = "NONE"
fade_in = 10
fade_out = 10
volume = 80
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_MetalMediumBashStone1'
file = 'Sound\Units\Combat\MetalMediumBashStone1.wav'
effects = 'CombatSoundsEAX'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_WoodLightBashStone3'
file = 'Sound\Units\Combat\WoodLightBashStone3.wav'
effects = 'CombatSoundsEAX'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_WoodLightBashStone2'
file = 'Sound\Units\Combat\WoodLightBashStone2.wav'
effects = 'CombatSoundsEAX'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0