# Warcraft 3 Map Objects File (.w3o)
# See w3o.py for type definitions
version = 2
has_levels = false

[blizzard_objects]
[[blizzard_objects.entities]]
parent_id = 'Umal'  # Dreadlord
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ua1t'  # UnitWeapons.Attack 1 - Attack Type
data_type = "String"
variation_level = 0
table_column = 0
value = "siege"
object_id = 'null'

[[blizzard_objects.entities.modifications]]
modification_id = 'uhab'  # UnitAbilities.Hero
data_type = "String"
variation_level = 0
table_column = 0
value = "ANsl,AUcs,AUsl,ANdc"
object_id = 'null'

[[blizzard_objects.entities.modifications]]
modification_id = 'ua1b'  # UnitWeapons.Attack 1 - Damage Base
data_type = "Integer"
variation_level = 0
table_column = 0
value = 10
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'nslf'  # Sludge Flinger
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ua1r'  # UnitWeapons.Attack 1 - Range
data_type = "Integer"
variation_level = 0
table_column = 0
value = 500
object_id = 'null'

[[blizzard_objects.entities.modifications]]
modification_id = 'ua1b'  # UnitWeapons.Attack 1 - Damage Base
data_type = "Integer"
variation_level = 0
table_column = 0
value = 0
object_id = 'null'

[[blizzard_objects.entities.modifications]]
modification_id = 'ua1d'  # UnitWeapons.Attack 1 - Damage Number of Dice
data_type = "Integer"
variation_level = 0
table_column = 0
value = 0
object_id = 'null'

[[blizzard_objects.entities.modifications]]
modification_id = 'ua1s'  # UnitWeapons.Attack 1 - Damage Sides per Die
data_type = "Integer"
variation_level = 0
table_column = 0
value = 0
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'nrat'  # Rat
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'umvs'  # UnitBalance.Speed Base
data_type = "Integer"
variation_level = 0
table_column = 0
value = 400
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'nltl'  # Lightning Lizard
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'umvs'  # UnitBalance.Speed Base
data_type = "Integer"
variation_level = 0
table_column = 0
value = 320
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'ngme'  # Goblin Merchant
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'usei'  # Profile.Items Sold
data_type = "String"
variation_level = 0
table_column = 0
value = "phea,pman,shea,spro,wneg,gemt,stwp"
object_id = 'null'

[[blizzard_objects.entities.modifications]]
modification_id = 'usma'  # UnitBalance.Stock Maximum
data_type = "Integer"
variation_level = 0
table_column = 0
value = 3
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'hfoo'  # Footman
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'uabi'  # UnitAbilities.Normal
data_type = "String"
variation_level = 0
table_column = 0
value = "Adef,Aihn,AP00"
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'nenf'  # Enforcer
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ubba'  # UnitBalance.Gold Bounty Awarded - Base
data_type = "Integer"
variation_level = 0
table_column = 0
value = 40
object_id = 'null'

[map_objects]
[[map_objects.entities]]
parent_id = 'nvil'  # Villager
entity_id = 'nC00'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = "Plagued Male Villager"
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'uclb'  # UnitUI.Tinting Color 3 (Blue)
data_type = "Integer"
variation_level = 0
table_column = 0
value = 125
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'uclr'  # UnitUI.Tinting Color 1 (Red)
data_type = "Integer"
variation_level = 0
table_column = 0
value = 125
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'umvs'  # UnitBalance.Speed Base
data_type = "Integer"
variation_level = 0
table_column = 0
value = 100
object_id = 'null'

[[map_objects.entities]]
parent_id = 'nvlw'  # Villager
entity_id = 'nC01'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = "Plagued Female Villager"
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'uclr'  # UnitUI.Tinting Color 1 (Red)
data_type = "Integer"
variation_level = 0
table_column = 0
value = 125
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'uclb'  # UnitUI.Tinting Color 3 (Blue)
data_type = "Integer"
variation_level = 0
table_column = 0
value = 125
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'umvs'  # UnitBalance.Speed Base
data_type = "Integer"
variation_level = 0
table_column = 0
value = 100
object_id = 'null'

[[map_objects.entities]]
parent_id = 'nvlk'  # Child
entity_id = 'nC02'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = "Plagued Child Villager"
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'uclr'  # UnitUI.Tinting Color 1 (Red)
data_type = "Integer"
variation_level = 0
table_column = 0
value = 125
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'uclb'  # UnitUI.Tinting Color 3 (Blue)
data_type = "Integer"
variation_level = 0
table_column = 0
value = 125
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'umvs'  # UnitBalance.Speed Base
data_type = "Integer"
variation_level = 0
table_column = 0
value = 90
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'uabi'  # UnitAbilities.Normal
data_type = "String"
variation_level = 0
table_column = 0
value = "Apts"
object_id = 'null'

[[map_objects.entities]]
parent_id = 'nzom'  # Zombie
entity_id = 'nC03'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = "''Zombie of Mal'Ganis''"
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'usca'  # UnitUI.Scaling Value
data_type = "Float"
variation_level = 0
table_column = 0
value = 1.75
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'uhpm'  # UnitBalance.Hit Points Maximum (Base)
data_type = "Integer"
variation_level = 0
table_column = 0
value = 800
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'uhpr'  # UnitBalance.Hit Points Regeneration Rate
data_type = "Unreal"
variation_level = 0
table_column = 0
value = 3.0
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ua1d'  # UnitWeapons.Attack 1 - Damage Number of Dice
data_type = "Integer"
variation_level = 0
table_column = 0
value = 20
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ua1s'  # UnitWeapons.Attack 1 - Damage Sides per Die
data_type = "Integer"
variation_level = 0
table_column = 0
value = 10
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'umvs'  # UnitBalance.Speed Base
data_type = "Integer"
variation_level = 0
table_column = 0
value = 225
object_id = 'null'

[[map_objects.entities]]
parent_id = 'nvl2'  # Villager
entity_id = 'nC04'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = "Plagued Male Villager"
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'uclr'  # UnitUI.Tinting Color 1 (Red)
data_type = "Integer"
variation_level = 0
table_column = 0
value = 125
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'uclb'  # UnitUI.Tinting Color 3 (Blue)
data_type = "Integer"
variation_level = 0
table_column = 0
value = 125
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'umvs'  # UnitBalance.Speed Base
data_type = "Integer"
variation_level = 0
table_column = 0
value = 120
object_id = 'null'

[[map_objects.entities]]
parent_id = 'Umal'  # Dreadlord
entity_id = 'UC05'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = "CONVERSIONMAN"
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'upro'  # Profile.Proper Names
data_type = "String"
variation_level = 0
table_column = 0
value = "Conversion Man"
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'umvt'  # UnitData.Type
data_type = "String"
variation_level = 0
table_column = 0
value = "fly"
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'uhab'  # UnitAbilities.Hero
data_type = "String"
variation_level = 0
table_column = 0
value = "SNdc"
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'umvh'  # UnitData.Height
data_type = "Unreal"
variation_level = 0
table_column = 0
value = 256.0
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'utpr'  # Profile.Tooltip - Revive
data_type = "String"
variation_level = 0
table_column = 0
value = "Revive Conversion Man"
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'umdl'  # UnitUI.Model File
data_type = "String"
variation_level = 0
table_column = 0
value = "units\\critters\\FlyingSheep\\FlyingSheep"
object_id = 'nshf'  # Flying Sheep

[[map_objects.entities.modifications]]
modification_id = 'uico'  # Profile.Icon - Game Interface
data_type = "String"
variation_level = 0
table_column = 0
value = "ReplaceableTextures\\CommandButtons\\BTNSheep.tga"
object_id = 'nshf'  # Flying Sheep

[[map_objects.entities.modifications]]
modification_id = 'umvr'  # UnitData.Turn Rate
data_type = "Unreal"
variation_level = 0
table_column = 0
value = 0.10000000149011612
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'umvs'  # UnitBalance.Speed Base
data_type = "Integer"
variation_level = 0
table_column = 0
value = 1000
object_id = 'null'

[[map_objects.entities]]
parent_id = 'nrat'  # Rat
entity_id = 'nC06'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = "Filson the Rat"
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'usca'  # UnitUI.Scaling Value
data_type = "Float"
variation_level = 0
table_column = 0
value = 1.5
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'uabi'  # UnitAbilities.Normal
data_type = "String"
variation_level = 0
table_column = 0
value = "Awan,Arng,ACes,ACmi"
object_id = 'null'

[[map_objects.entities]]
parent_id = 'hmil'  # Militia
entity_id = 'hA00'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = "Irregular"
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ua1b'  # UnitWeapons.Attack 1 - Damage Base
data_type = "Integer"
variation_level = 0
table_column = 0
value = 9
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'uabi'  # UnitAbilities.Normal
data_type = "String"
variation_level = 0
table_column = 0
value = "APPh"
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'udaa'  # UnitAbilities.Default Active Ability
data_type = "String"
variation_level = 0
table_column = 0
value = ""
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ubui'  # Profile.Structures Built
data_type = "String"
variation_level = 0
table_column = 0
value = ""
object_id = 'null'
