# Warcraft 3 Sound file (.w3s)
# See w3s.py for type definitions

version = 1

[[sounds]]

name = 'gg_snd_H08Arthas06'
file = 'Sound\Dialogue\HumanCampaign\Human08\H08Arthas06.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H08Arthas08'
file = 'Sound\Dialogue\HumanCampaign\Human08\H08Arthas08.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H08Arthas10'
file = 'Sound\Dialogue\HumanCampaign\Human08\H08Arthas10.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H08Arthas11'
file = 'Sound\Dialogue\HumanCampaign\Human08\H08Arthas11.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H08Arthas13'
file = 'Sound\Dialogue\HumanCampaign\Human08\H08Arthas13.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H08Arthas18'
file = 'Sound\Dialogue\HumanCampaign\Human08\H08Arthas18.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H08Arthas19'
file = 'Sound\Dialogue\HumanCampaign\Human08\H08Arthas19.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H08Arthas21'
file = 'Sound\Dialogue\HumanCampaign\Human08\H08Arthas21.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H08Arthas25'
file = 'Sound\Dialogue\HumanCampaign\Human08\H08Arthas25.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H08Captain01'
file = 'Sound\Dialogue\HumanCampaign\Human08\H08Captain01.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H08Captain03'
file = 'Sound\Dialogue\HumanCampaign\Human08\H08Captain03.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H08Captain05'
file = 'Sound\Dialogue\HumanCampaign\Human08\H08Captain05.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H08Captain07'
file = 'Sound\Dialogue\HumanCampaign\Human08\H08Captain07.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H08Captain20'
file = 'Sound\Dialogue\HumanCampaign\Human08\H08Captain20.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H08Emissary02'
file = 'Sound\Dialogue\HumanCampaign\Human08\H08Emissary02.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H08Emissary04'
file = 'Sound\Dialogue\HumanCampaign\Human08\H08Emissary04.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H08Footman16'
file = 'Sound\Dialogue\HumanCampaign\Human08\H08Footman16.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H08Footman22'
file = 'Sound\Dialogue\HumanCampaign\Human08\H08Footman22.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H08Footman24'
file = 'Sound\Dialogue\HumanCampaign\Human08\H08Footman24.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H08Knight23'
file = 'Sound\Dialogue\HumanCampaign\Human08\H08Knight23.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H08Muradin09'
file = 'Sound\Dialogue\HumanCampaign\Human08\H08Muradin09.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_H08Muradin12'
file = 'Sound\Dialogue\HumanCampaign\Human08\H08Muradin12.mp3'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_Loading'
file = 'Abilities\Spells\Other\LoadUnload\Loading.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_Hint'
file = 'Sound\Interface\Hint.wav'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_QuestCompleted'
file = 'Sound\Interface\QuestCompleted.wav'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_QuestFailed'
file = 'Sound\Interface\QuestFailed.wav'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_QuestLog'
file = 'Sound\Interface\QuestLog.wav'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_QuestNew'
file = 'Sound\Interface\QuestNew.wav'
effects = ''
flags = "NONE"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_WaterWavesLoop1'
file = 'Sound\Ambient\DoodadEffects\WaterWavesLoop1.wav'
effects = 'DoodadsEAX'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0

[[sounds]]

name = 'gg_snd_HorseLoop2'
file = 'Units\Human\Knight\HorseLoop2.wav'
effects = 'DefaultEAXON'
flags = "Three_D|Stop_Outside_Range"
fade_in = 10
fade_out = 10
volume = -1
pitch = 4294967296.0
channel = "Default"
min_distance = 4294967296.0
max_distance = 4294967296.0
distance_cutoff = 4294967296.0