# Warcraft 3 Map Objects File (.w3o)
# See w3o.py for type definitions
version = 2
has_levels = false

[blizzard_objects]
[[blizzard_objects.entities]]
parent_id = 'nass'  # Assassin
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'uabi'  # UnitAbilities.Normal
data_type = "String"
variation_level = 0
table_column = 0
value = "ACvs"
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'nrog'  # Rogue
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'uabi'  # UnitAbilities.Normal
data_type = "String"
variation_level = 0
table_column = 0
value = ""
object_id = 'null'

[[blizzard_objects.entities.modifications]]
modification_id = 'ubba'  # UnitBalance.Gold Bounty Awarded - Base
data_type = "Integer"
variation_level = 0
table_column = 0
value = 40
object_id = 'null'

[[blizzard_objects.entities.modifications]]
modification_id = 'ubdi'  # UnitBalance.Gold Bounty Awarded - Number of Dice
data_type = "Integer"
variation_level = 0
table_column = 0
value = 3
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'nenf'  # Enforcer
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'uabi'  # UnitAbilities.Normal
data_type = "String"
variation_level = 0
table_column = 0
value = "ACev"
object_id = 'null'

[[blizzard_objects.entities.modifications]]
modification_id = 'ubba'  # UnitBalance.Gold Bounty Awarded - Base
data_type = "Integer"
variation_level = 0
table_column = 0
value = 40
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'nbrg'  # Brigand
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'uabi'  # UnitAbilities.Normal
data_type = "String"
variation_level = 0
table_column = 0
value = ""
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'nban'  # Bandit
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'uabi'  # UnitAbilities.Normal
data_type = "String"
variation_level = 0
table_column = 0
value = ""
object_id = 'null'

[[blizzard_objects.entities.modifications]]
modification_id = 'ubba'  # UnitBalance.Gold Bounty Awarded - Base
data_type = "Integer"
variation_level = 0
table_column = 0
value = 25
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'nbld'  # Bandit Lord
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'uabi'  # UnitAbilities.Normal
data_type = "String"
variation_level = 0
table_column = 0
value = "ACav,ACds"
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'nmrl'  # Murloc Tiderunner
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ubba'  # UnitBalance.Gold Bounty Awarded - Base
data_type = "Integer"
variation_level = 0
table_column = 0
value = 25
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'nmrr'  # Murloc Huntsman
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ubba'  # UnitBalance.Gold Bounty Awarded - Base
data_type = "Integer"
variation_level = 0
table_column = 0
value = 30
object_id = 'null'

[[blizzard_objects.entities.modifications]]
modification_id = 'ubdi'  # UnitBalance.Gold Bounty Awarded - Number of Dice
data_type = "Integer"
variation_level = 0
table_column = 0
value = 2
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'nogm'  # Ogre Mauler
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ubba'  # UnitBalance.Gold Bounty Awarded - Base
data_type = "Integer"
variation_level = 0
table_column = 0
value = 70
object_id = 'null'

[[blizzard_objects.entities.modifications]]
modification_id = 'ubdi'  # UnitBalance.Gold Bounty Awarded - Number of Dice
data_type = "Integer"
variation_level = 0
table_column = 0
value = 5
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'nogr'  # Ogre Warrior
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ubba'  # UnitBalance.Gold Bounty Awarded - Base
data_type = "Integer"
variation_level = 0
table_column = 0
value = 40
object_id = 'null'

[[blizzard_objects.entities.modifications]]
modification_id = 'ubdi'  # UnitBalance.Gold Bounty Awarded - Number of Dice
data_type = "Integer"
variation_level = 0
table_column = 0
value = 3
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'hfoo'  # Footman
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'uabi'  # UnitAbilities.Normal
data_type = "String"
variation_level = 0
table_column = 0
value = "Adef,Aihn,AP00"
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'Hpal'  # Paladin
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ufoo'  # UnitBalance.Food Cost
data_type = "Integer"
variation_level = 0
table_column = 0
value = 0
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'Hamg'  # Archmage
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ufoo'  # UnitBalance.Food Cost
data_type = "Integer"
variation_level = 0
table_column = 0
value = 0
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'Hmkg'  # Mountain King
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ufoo'  # UnitBalance.Food Cost
data_type = "Integer"
variation_level = 0
table_column = 0
value = 0
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'Hblm'  # Blood Mage
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ufoo'  # UnitBalance.Food Cost
data_type = "Integer"
variation_level = 0
table_column = 0
value = 0
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'Udea'  # Death Knight
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ufoo'  # UnitBalance.Food Cost
data_type = "Integer"
variation_level = 0
table_column = 0
value = 0
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'Ulic'  # Lich
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ufoo'  # UnitBalance.Food Cost
data_type = "Integer"
variation_level = 0
table_column = 0
value = 0
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'Udre'  # Dreadlord
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ufoo'  # UnitBalance.Food Cost
data_type = "Integer"
variation_level = 0
table_column = 0
value = 0
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'Ucrl'  # Crypt Lord
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ufoo'  # UnitBalance.Food Cost
data_type = "Integer"
variation_level = 0
table_column = 0
value = 0
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'Obla'  # Blademaster
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ufoo'  # UnitBalance.Food Cost
data_type = "Integer"
variation_level = 0
table_column = 0
value = 0
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'Ofar'  # Far Seer
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ufoo'  # UnitBalance.Food Cost
data_type = "Integer"
variation_level = 0
table_column = 0
value = 0
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'Otch'  # Tauren Chieftain
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ufoo'  # UnitBalance.Food Cost
data_type = "Integer"
variation_level = 0
table_column = 0
value = 0
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'Oshd'  # Shadow Hunter
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ufoo'  # UnitBalance.Food Cost
data_type = "Integer"
variation_level = 0
table_column = 0
value = 0
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'Emoo'  # Priestess of the Moon
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ufoo'  # UnitBalance.Food Cost
data_type = "Integer"
variation_level = 0
table_column = 0
value = 0
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'Ekee'  # Keeper of the Grove
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ufoo'  # UnitBalance.Food Cost
data_type = "Integer"
variation_level = 0
table_column = 0
value = 0
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'Edem'  # Demon Hunter
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ufoo'  # UnitBalance.Food Cost
data_type = "Integer"
variation_level = 0
table_column = 0
value = 0
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'Ewar'  # Warden
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ufoo'  # UnitBalance.Food Cost
data_type = "Integer"
variation_level = 0
table_column = 0
value = 0
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'Nalc'  # Alchemist
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ufoo'  # UnitBalance.Food Cost
data_type = "Integer"
variation_level = 0
table_column = 0
value = 0
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'Nbst'  # Beastmaster
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ufoo'  # UnitBalance.Food Cost
data_type = "Integer"
variation_level = 0
table_column = 0
value = 0
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'Nbrn'  # Dark Ranger
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ufoo'  # UnitBalance.Food Cost
data_type = "Integer"
variation_level = 0
table_column = 0
value = 0
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'Nfir'  # Firelord
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ufoo'  # UnitBalance.Food Cost
data_type = "Integer"
variation_level = 0
table_column = 0
value = 0
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'Ntin'  # Tinker
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ufoo'  # UnitBalance.Food Cost
data_type = "Integer"
variation_level = 0
table_column = 0
value = 0
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'Nngs'  # Naga Sea Witch
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ufoo'  # UnitBalance.Food Cost
data_type = "Integer"
variation_level = 0
table_column = 0
value = 0
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'Npbm'  # Pandaren Brewmaster
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ufoo'  # UnitBalance.Food Cost
data_type = "Integer"
variation_level = 0
table_column = 0
value = 0
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'Nplh'  # Pit Lord
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ufoo'  # UnitBalance.Food Cost
data_type = "Integer"
variation_level = 0
table_column = 0
value = 0
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'Naka'  # Elder Sage
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ufoo'  # UnitBalance.Food Cost
data_type = "Integer"
variation_level = 0
table_column = 0
value = 0
object_id = 'null'

[[blizzard_objects.entities]]
parent_id = 'Ekgg'  # Keeper of the Grove
entity_id = 'null'
[[blizzard_objects.entities.modifications]]
modification_id = 'ufoo'  # UnitBalance.Food Cost
data_type = "Integer"
variation_level = 0
table_column = 0
value = 0
object_id = 'null'

[map_objects]
[[map_objects.entities]]
parent_id = 'nvlw'  # Villager
entity_id = 'nC00'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = "Stacie"
object_id = 'null'

[[map_objects.entities]]
parent_id = 'nvl2'  # Villager
entity_id = 'nC01'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = "Garglemel"
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ubdi'  # UnitBalance.Gold Bounty Awarded - Number of Dice
data_type = "Integer"
variation_level = 0
table_column = 0
value = 5
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ubsi'  # UnitBalance.Gold Bounty Awarded - Sides per Die
data_type = "Integer"
variation_level = 0
table_column = 0
value = 20
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ubba'  # UnitBalance.Gold Bounty Awarded - Base
data_type = "Integer"
variation_level = 0
table_column = 0
value = 10
object_id = 'null'

[[map_objects.entities]]
parent_id = 'nvl2'  # Villager
entity_id = 'nC02'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = "Achilles"
object_id = 'null'

[[map_objects.entities]]
parent_id = 'nvl2'  # Villager
entity_id = 'nC03'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = "Alric"
object_id = 'null'

[[map_objects.entities]]
parent_id = 'nvlw'  # Villager
entity_id = 'nC04'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = "Marie Claire Antoinette"
object_id = 'null'

[[map_objects.entities]]
parent_id = 'nvlw'  # Villager
entity_id = 'nC05'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = "Alizabeth"
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'usca'  # UnitUI.Scaling Value
data_type = "Float"
variation_level = 0
table_column = 0
value = 0.800000011920929
object_id = 'null'

[[map_objects.entities]]
parent_id = 'nvlk'  # Child
entity_id = 'nC06'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = "Alex"
object_id = 'null'

[[map_objects.entities]]
parent_id = 'nvlk'  # Child
entity_id = 'nC07'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = "Austen"
object_id = 'null'

[[map_objects.entities]]
parent_id = 'nvlw'  # Villager
entity_id = 'nC08'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = "Linda"
object_id = 'null'

[[map_objects.entities]]
parent_id = 'nvlw'  # Villager
entity_id = 'nC09'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = "Jillian"
object_id = 'null'

[[map_objects.entities]]
parent_id = 'nvlw'  # Villager
entity_id = 'nC10'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = "Splendora"
object_id = 'null'

[[map_objects.entities]]
parent_id = 'nvlw'  # Villager
entity_id = 'nC11'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = "Daunell Barton"
object_id = 'null'

[[map_objects.entities]]
parent_id = 'hmil'  # Militia
entity_id = 'hA00'
[[map_objects.entities.modifications]]
modification_id = 'unam'  # Profile.Name
data_type = "String"
variation_level = 0
table_column = 0
value = "Irregular"
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ua1b'  # UnitWeapons.Attack 1 - Damage Base
data_type = "Integer"
variation_level = 0
table_column = 0
value = 9
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'uabi'  # UnitAbilities.Normal
data_type = "String"
variation_level = 0
table_column = 0
value = "APPh"
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'udaa'  # UnitAbilities.Default Active Ability
data_type = "String"
variation_level = 0
table_column = 0
value = ""
object_id = 'null'

[[map_objects.entities.modifications]]
modification_id = 'ubui'  # Profile.Structures Built
data_type = "String"
variation_level = 0
table_column = 0
value = ""
object_id = 'null'
